### PR TITLE
Fix: config-dev to config

### PR DESCRIPTION
**Pull request by shreelakshmijoshi**
Updated config-dev.json to config.json. Link : https://github.com/datakaveri/iudx-gis-interface/pull/124#issuecomment-2219717761
Refactored : 
- [config-dev to config](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/aa027f2cbc4a7df40e23d0b86ff2775641cf1e5c)
-  [Redundant, unnecessary config](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/749b82d3cf0cd866647aa6f8f158f12376a7175b)
- [IUDX to DX](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/9f3121eb7b31b49223139b9412701d582fda8fde)
- [Updated collection](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/df25a9e6397cf2023431fef8f8611640b0d23712)
- [Remove unused variable](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/c8275ed55791aa15fc70874b1dc344705762dbdf)

Ideas contributed by @abhi4578 
- [Db configs](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/4c80084811d4a909378aeb6f4e3be64d91b4daca)
- [README, Configurations](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/a2642e6df0318b5dd115e9f1c8bd696244f9b03e)
- [Remove host](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/068ce4fc7b7fa2029b013d03d8ff758fbba1b480)
- [Remove ssl](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/2814ab5a04831348f5b1c1c73346690dfeccc1a2)
- [Remove domain](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/6ffee13a691a7da7f39a6b1d2e8754979b3b957b)

### CODE REVIEW

**Review by abhi4578 — CHANGES_REQUESTED** [review]
- Even in the example configs directory, please rename the file to [config.json](https://github.com/datakaveri/iudx-acl-apd/blob/main/example-config/config-dev.json) from config-dev.json 

Some configuration options that we can remove , which are not used. 
So that the config becomes more cleaner and easier to configure the server

- "prodVhost": "\<prod-vHost-name\>",
- "internalVhost": "\<internal-vHost-name\>",
- "externalVhost": "\<external-vHost-name\>"
-   "host": "acl-apd.iudx.io" --> This is not really used, for clustering the host value is dynamic - based on container hostname/POD IP and is passed command line param while running the jar - https://github.com/datakaveri/iudx-acl-apd/blob/bfb8ac8e4486631239c5e8a8dbb3e3d82df9d199/src/main/java/iudx/apd/acl/server/deploy/Deployer.java#L363

**Comment by shreelakshmijoshi** [comment]
> * Even in the example configs directory, please rename the file to [config.json](https://github.com/datakaveri/iudx-acl-apd/blob/main/example-config/config-dev.json) from config-dev.json
> 
> Some configuration options that we can remove , which are not used. So that the config becomes more cleaner and easier to configure the server
> 
> * "prodVhost": "<prod-vHost-name

Thanks for reviewing, added the changes in these commits : [aa027f2](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/aa027f2cbc4a7df40e23d0b86ff2775641cf1e5c), [749b82d](https://github.com/datakaveri/iudx-acl-apd/pull/160/commits/749b82d3cf0cd866647aa6f8f158f12376a7175b)

- About removing `host` even though it might not be used in Deployer.java for production, it is being used in `DeployerDev.java` for non-clustered deployments like dev environments
- https://github.com/datakaveri/iudx-acl-apd/blob/bfb8ac8e4486631239c5e8a8dbb3e3d82df9d199/src/main/java/iudx/apd/acl/server/deploy/DeployerDev.java#L39
- I'm guessing both clustered and non-clustered deployments use a single config, please do correct me if I'm wrong

**Comment by abhi4578** [comment]
>     * About removing `host` even though it might not be used in Deployer.java for production, it is being used in `DeployerDev.java` for non-clustered deployments like dev environments
> 
>     * https://github.com/datakaveri/iudx-acl-apd/blob/bfb8ac8e4486631239c5e8a8dbb3e3d82df9d199/src/main/java/iudx/apd/acl/server/deploy/DeployerDev.java#L39
> 
>     * I'm guessing both clustered and non-clustered deployments use a single config, please do correct me if I'm wrong

- Even in deployerDev its not being used anywhere finally, following line can be removed. 
https://github.com/datakaveri/iudx-acl-apd/blob/bfb8ac8e4486631239c5e8a8dbb3e3d82df9d199/src/main/java/iudx/apd/acl/server/deploy/DeployerDev.java#L39 
 Ref: https://github.com/search?q=repo%3Adatakaveri%2Fiudx-acl-apd+host&type=code&p=2 
 
 - Also we can club DeployerDev.java and Deployer.java. Will create an feature  issue of  the  same

**Comment by shreelakshmijoshi** [comment]
retest this please

**Review by abhi4578 — APPROVED** [review]
All the changes looks good , I have removed keystore-file.jks file from compose file.

**Pull request merged**
